# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master
  - develop
  - feature/*

variables:
  NODE_VERSION: 10

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      steps:
      - task: UseNode@1
        inputs:
          version: '$NODE_VERSION.x'
      - script: echo Building! $(NODE_VERSION)
      - bash: npm ci
  - stage: Test
    jobs:
    - job: Test_Lint
      steps:
      - script: npm run check-lint
    - job: Test_Unit
      steps:
      - script: npm run test
    - job: Test_E2E
      steps:
      - script: npm run e2e
  - stage: Deploy
    jobs:
    - job: Deploy
      steps:
      - script: echo Deploying the code!