# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  - master
  - develop
  - feature/*

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      steps:
      - task: Npm@1
        displayName: 'npm install'
        inputs:
          command: 'ci'
      - task: Npm@1
        displayName: 'Build proyect'
        inputs:
          command: custom
          customCommand: run build -- --prod
      
  - stage: Test
    jobs:
    - job: Test_Lint
      steps:
      - template: azure/templates/install_packages.yml  # Template of build
      - script: npm run check-lint
    - job: Test_Unit
      steps:
      - template: azure/templates/install_packages.yml  # Template of build
      - script: npm run test
    - job: Test_E2E
      steps:
      - template: azure/templates/install_packages.yml  # Template of build
      - script: npm run e2e
  - stage: Deploy
    jobs:
    - job: Deploy
      steps:
      - script: echo Deploying the code!